name: deploy-all
on:
  push:
    branches:
      -feature/github-actions
env:
  GITHUB_SECRET: ${{ secrets.SECRET_A }}
  LAUREN_SECRET: BENTLEY
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: bash ./config/deploy.sh
  get-secret-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $LAUREN_SECRET
      - run: echo $GITHUB_SECRET
