name: learn-github-actions
on: [push]
env:
  GITHUB_SECRET: ${{ secrets.SECRET_A }}
  LAUREN_SECRET: BENTLEY
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install

  get-secret-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $LAUREN_SECRET
      - run: echo $GITHUB_SECRET
  cdk-synth:
    runs-on: ubuntu-latest
    steps:
    - name: cdk synth
      uses: youyo/aws-cdk-github-actions@v1
      with:
        cdk_subcommand: 'synth'
        actions_comment: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2'
        AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_DEFAULT_ACCOUNT }}
  cdk-diff:
    runs-on: ubuntu-latest
    steps:
    - name: cdk diff
      uses: youyo/aws-cdk-github-actions@v1
      with:
        cdk_subcommand: 'diff'
        actions_comment: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2'
        AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_DEFAULT_ACCOUNT }}
